Capsula.destroy_all

Capsula.create(name: 'Caffè Matinal', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '21 segundos', tipo_id: 2 )
Capsula.create(name: 'Duo Matinal', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '28 (Cafe Au Lait) e  21 segundos (Caffè Matinal)', tipo_id: 2 )
Capsula.create(name: 'Lungo', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '21 segundos', tipo_id: 2 )
Capsula.create(name: 'Cappuccino', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula preta: 28 segundos e Capsula branca: 08 segundos', tipo_id: 3 )
Capsula.create(name: 'Caramel Latte Macchiato', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula preta: 10 segundos e Capsula branca: 24 segundos', tipo_id: 3 )
Capsula.create(name: 'Cortado', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '15 segundos', tipo_id: 3 )
Capsula.create(name: 'Latte Macchiato', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula preta: 10 segundos e Capsula branca: 24 segundos', tipo_id: 3 )
Capsula.create(name: 'Vanilla Latte Macchiato', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula preta: 28 segundos e Capsula branca: 24 segundos', tipo_id: 3 )
Capsula.create(name: 'Chococino', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula marrom: 15 segundos e Capsula branca: 15 segundos', tipo_id: 4 )
Capsula.create(name: 'Chococino Caramel', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula marrom: 15 segundos e Capsula branca: 15 segundos', tipo_id: 4 )
Capsula.create(name: 'Mocha', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: 'Capsula marrom: 15 segundos e Capsula branca: 15 segundos', tipo_id: 4 )
Capsula.create(name: 'Nescao', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '21 segundos', tipo_id: 4 )
Capsula.create(name: 'Ristreto', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '08 segundos', tipo_id: 1 )
Capsula.create(name: 'Espresso Intenso', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '10 segundos', tipo_id: 1 )
Capsula.create(name: 'Espresso Decafeinato', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '10 segundos', tipo_id: 1 )
Capsula.create(name: 'Ristreto Ardenza', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '08 segundos', tipo_id: 1 )
Capsula.create(name: 'Espresso Barista', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '08 segundos', tipo_id: 1 )
Capsula.create(name: 'Nestea Limao', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo frio', tempo_preparo: '30 segundos', tipo_id: 5 )
Capsula.create(name: 'Nestea Pessego', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo frio', tempo_preparo: '30 segundos', tipo_id: 5 )
Capsula.create(name: 'Chati Tea Latte', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo frio', tempo_preparo: 'Capsula marrom: 15 segundos e Capsula branca: 15 segundos', tipo_id: 6 )
Capsula.create(name: 'Marrakesh Style Tea', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo frio', tempo_preparo: '28 segundos', tipo_id: 6 )
Capsula.create(name: 'Espresso', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '08 segundos', tipo_id: 1 )
Capsula.create(name: 'Cafe Au Lait', instrucoes_preparo: 'Acione a alavanca para a posição de fluxo quente', tempo_preparo: '28 segundos', tipo_id: 2 )  